site_name: Endgame
site_url: https://endgame.readthedocs.io/
repo_url: https://github.com/salesforce/endgame/
theme: material
use_directory_urls: true
markdown_extensions:
    - codehilite
    - tables
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - endgame/
extra_css:
  - custom.css
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Tutorial: 'tutorial.md'
  - Permissions: 'iam-permissions.md'

  - "<b>Backdoor Resource Types</b>":
    - ACM Private CAs: 'risks/acm-pca.md'
    - CloudWatch: 'risks/cloudwatch-logs.md'
    - EC2 Machine Images (AMIs): 'risks/ec2-amis.md'
    - Elastic Block Store (EBS): 'risks/ebs.md'
    - Elastic Container Registry (ECR): 'risks/ecr.md'
    - Elastic File System (EFS): 'risks/elasticfilesystem.md'
    - ElasticSearch: 'risks/elasticsearch.md'
    - Glacier Vaults: 'risks/glacier.md'
    - IAM Roles: 'risks/iam.md'
    - KMS Keys: 'risks/kms.md'
    - Lambda Functions: 'risks/lambda-functions.md'
    - Lambda Layers: 'risks/lambda-layers.md'
    - RDS Snapshots: 'risks/rds-snapshots.md'
    - S3 Buckets: 'risks/s3.md'
    - Secrets Manager: 'risks/secretsmanager.md'
    - SES: 'risks/ses.md'
    - SNS: 'risks/sns.md'
    - SQS: 'risks/sqs.md'

  - "<b>Contributing</b>":
    - Contributing: 'contributing/contributing.md'
    - Testing: 'contributing/testing.md'
